In [1]:
print("hello")

hello


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
b = np.array([4, 5, 6])

In [7]:
type(b)

numpy.ndarray

In [8]:
c = [1, 2, 3]

In [9]:
type(c)

list

In [10]:
c = np.array(c)

In [11]:
type(c)

numpy.ndarray

In [12]:
c

array([1, 2, 3])

In [13]:
a = np.array([1, 2, 3, 4], dtype = dict)

In [14]:
a

array([1, 2, 3, 4], dtype=object)

In [15]:
for i in np.arange(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [16]:
a = np.array([1, 2, 3])

# [1, 
#  2, 
#  3]

In [17]:
a.shape

(3,)

In [18]:
a = np.array([[1, 2, 3]])

In [19]:
a.shape

(1, 3)

In [20]:
# (4, ) 
# (4, 5)

In [21]:
[[1, 1, 1], 
 [1, 1, 1],
 [1, 1, 1]]

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [22]:
import numpy as np
x = np.identity(5)

In [23]:
x.shape

(5, 5)

In [24]:
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
x = np.ones((3, 5), dtype = str)

In [26]:
x

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [27]:
x = np.zeros((3, 4))

In [28]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
x = np.random.random((3, 4))

In [30]:
x

array([[0.76759938, 0.72617557, 0.50676355, 0.9643535 ],
       [0.93460444, 0.76643842, 0.48932948, 0.05686811],
       [0.7647539 , 0.44601765, 0.55788496, 0.4149745 ]])

In [31]:
np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method

In [32]:
# [3, 6)

In [33]:
np.linspace(-10, 10, 100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [34]:
-10-(-8)

-2

In [35]:
-8 - (-6)

-2

In [36]:
a1 = np.arange(10, dtype = int)
a2 = np.arange(12, dtype = float)
a3 = np.arange(8)

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a1.ndim

1

In [39]:
a1.size

10

In [40]:
a1.dtype

dtype('int32')

In [41]:
a1 = a1.astype(float)

In [42]:
a1.dtype

dtype('float64')

In [43]:
# scalar operations
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
a1 ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [45]:
a2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [46]:
# relational
a2 == 15
# a2

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [47]:
a1 ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [48]:
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
x = np.array([[1, 2], 
              [3, 4]])

y = np.array([[5, 6], 
              [7, 8]])

In [50]:
x + y

array([[ 6,  8],
       [10, 12]])

In [51]:
x * y

array([[ 5, 12],
       [21, 32]])

In [52]:
x - y

array([[-4, -4],
       [-4, -4]])

In [53]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [54]:
x % y

array([[1, 2],
       [3, 4]])

In [55]:
x // y

array([[0, 0],
       [0, 0]])

In [56]:
np.add(x, y)

array([[ 6,  8],
       [10, 12]])

In [57]:
np.subtract(x, y)

array([[-4, -4],
       [-4, -4]])

In [58]:
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [59]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [60]:
a1 = np.random.random((3, 3))

In [61]:
a1 = np.round(a1)

In [62]:
a1

array([[0., 0., 0.],
       [1., 0., 1.],
       [0., 0., 1.]])

In [63]:
x

array([[1, 2],
       [3, 4]])

In [64]:
y

array([[5, 6],
       [7, 8]])

In [65]:
np.sum(x, axis = 0) # row wise operation

array([4, 6])

In [ ]:
np.sum(x, axis = 1) # col wise operation

array([3, 7])

In [67]:
x

array([[1, 2],
       [3, 4]])

In [68]:
y


array([[5, 6],
       [7, 8]])

In [69]:
x * y

array([[ 5, 12],
       [21, 32]])

In [70]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [71]:
np.dot(x, y)

array([[19, 22],
       [43, 50]])

In [72]:
np.matmul(x, y)

array([[19, 22],
       [43, 50]])

In [73]:
np.exp(a1)

array([[1.        , 1.        , 1.        ],
       [2.71828183, 1.        , 2.71828183],
       [1.        , 1.        , 2.71828183]])

In [74]:
a1

array([[0., 0., 0.],
       [1., 0., 1.],
       [0., 0., 1.]])

In [75]:
x

array([[1, 2],
       [3, 4]])

In [76]:
x[0]

array([1, 2])

In [77]:
x = np.random.random((5, 8))

In [78]:
x.shape

(5, 8)

In [79]:
x

array([[0.13645365, 0.46971305, 0.04304489, 0.04552481, 0.75760756,
        0.94316053, 0.73870004, 0.31444067],
       [0.39358168, 0.78803813, 0.19839427, 0.7170903 , 0.8810037 ,
        0.06811808, 0.518638  , 0.87585831],
       [0.2636058 , 0.31053057, 0.0309093 , 0.98887425, 0.22828072,
        0.47891392, 0.99892029, 0.93652518],
       [0.75987081, 0.06672226, 0.8546943 , 0.27600826, 0.77191441,
        0.56703443, 0.46878971, 0.28046498],
       [0.284716  , 0.87734164, 0.27693446, 0.37881555, 0.05729515,
        0.25941785, 0.95908605, 0.60676582]])

In [80]:
x[0]

array([0.13645365, 0.46971305, 0.04304489, 0.04552481, 0.75760756,
       0.94316053, 0.73870004, 0.31444067])

In [81]:
# ( r, c)
# x[ : ]

In [82]:
x[ 0 : 2, : ]

array([[0.13645365, 0.46971305, 0.04304489, 0.04552481, 0.75760756,
        0.94316053, 0.73870004, 0.31444067],
       [0.39358168, 0.78803813, 0.19839427, 0.7170903 , 0.8810037 ,
        0.06811808, 0.518638  , 0.87585831]])

In [83]:
x[3, : 4]

array([0.75987081, 0.06672226, 0.8546943 , 0.27600826])

In [84]:
x[0, 4]

0.7576075553317044

In [85]:
x

array([[0.13645365, 0.46971305, 0.04304489, 0.04552481, 0.75760756,
        0.94316053, 0.73870004, 0.31444067],
       [0.39358168, 0.78803813, 0.19839427, 0.7170903 , 0.8810037 ,
        0.06811808, 0.518638  , 0.87585831],
       [0.2636058 , 0.31053057, 0.0309093 , 0.98887425, 0.22828072,
        0.47891392, 0.99892029, 0.93652518],
       [0.75987081, 0.06672226, 0.8546943 , 0.27600826, 0.77191441,
        0.56703443, 0.46878971, 0.28046498],
       [0.284716  , 0.87734164, 0.27693446, 0.37881555, 0.05729515,
        0.25941785, 0.95908605, 0.60676582]])

In [86]:
x[[0, -1], : ]

array([[0.13645365, 0.46971305, 0.04304489, 0.04552481, 0.75760756,
        0.94316053, 0.73870004, 0.31444067],
       [0.284716  , 0.87734164, 0.27693446, 0.37881555, 0.05729515,
        0.25941785, 0.95908605, 0.60676582]])

In [87]:
x

array([[0.13645365, 0.46971305, 0.04304489, 0.04552481, 0.75760756,
        0.94316053, 0.73870004, 0.31444067],
       [0.39358168, 0.78803813, 0.19839427, 0.7170903 , 0.8810037 ,
        0.06811808, 0.518638  , 0.87585831],
       [0.2636058 , 0.31053057, 0.0309093 , 0.98887425, 0.22828072,
        0.47891392, 0.99892029, 0.93652518],
       [0.75987081, 0.06672226, 0.8546943 , 0.27600826, 0.77191441,
        0.56703443, 0.46878971, 0.28046498],
       [0.284716  , 0.87734164, 0.27693446, 0.37881555, 0.05729515,
        0.25941785, 0.95908605, 0.60676582]])

In [88]:
x[1 : 4 , : ]

array([[0.39358168, 0.78803813, 0.19839427, 0.7170903 , 0.8810037 ,
        0.06811808, 0.518638  , 0.87585831],
       [0.2636058 , 0.31053057, 0.0309093 , 0.98887425, 0.22828072,
        0.47891392, 0.99892029, 0.93652518],
       [0.75987081, 0.06672226, 0.8546943 , 0.27600826, 0.77191441,
        0.56703443, 0.46878971, 0.28046498]])

In [89]:
x[2, 2 : 5 ]

array([0.0309093 , 0.98887425, 0.22828072])

In [90]:
a1

array([[0., 0., 0.],
       [1., 0., 1.],
       [0., 0., 1.]])

In [93]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [94]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
a.shape

(2, 3)

In [96]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [97]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [99]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
a = a.T

In [101]:
a = np.transpose(a)

In [102]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
a.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]


In [112]:
a[0]

array([1, 2, 3])

In [ ]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6


In [113]:
a = np.random.random((4, 6))

In [114]:
a

array([[0.66139009, 0.55109088, 0.44117229, 0.78145   , 0.35673073,
        0.4724919 ],
       [0.35913307, 0.82487671, 0.9308465 , 0.55573379, 0.39736186,
        0.91822155],
       [0.89280326, 0.99244444, 0.93928608, 0.17169872, 0.39982916,
        0.36104625],
       [0.62088311, 0.50933936, 0.14757552, 0.46270758, 0.927096  ,
        0.47591423]])

In [116]:
a.T.shape

(6, 4)

In [117]:
x_transpose = a.T

In [118]:
x_transpose

array([[0.66139009, 0.35913307, 0.89280326, 0.62088311],
       [0.55109088, 0.82487671, 0.99244444, 0.50933936],
       [0.44117229, 0.9308465 , 0.93928608, 0.14757552],
       [0.78145   , 0.55573379, 0.17169872, 0.46270758],
       [0.35673073, 0.39736186, 0.39982916, 0.927096  ],
       [0.4724919 , 0.91822155, 0.36104625, 0.47591423]])

In [119]:
x_transpose = a.reshape(6, 4)

In [120]:
x_transpose

array([[0.66139009, 0.55109088, 0.44117229, 0.78145   ],
       [0.35673073, 0.4724919 , 0.35913307, 0.82487671],
       [0.9308465 , 0.55573379, 0.39736186, 0.91822155],
       [0.89280326, 0.99244444, 0.93928608, 0.17169872],
       [0.39982916, 0.36104625, 0.62088311, 0.50933936],
       [0.14757552, 0.46270758, 0.927096  , 0.47591423]])

In [121]:
a.reshape(12, 2)

array([[0.66139009, 0.55109088],
       [0.44117229, 0.78145   ],
       [0.35673073, 0.4724919 ],
       [0.35913307, 0.82487671],
       [0.9308465 , 0.55573379],
       [0.39736186, 0.91822155],
       [0.89280326, 0.99244444],
       [0.93928608, 0.17169872],
       [0.39982916, 0.36104625],
       [0.62088311, 0.50933936],
       [0.14757552, 0.46270758],
       [0.927096  , 0.47591423]])

In [122]:
a.reshape(8, 3)

array([[0.66139009, 0.55109088, 0.44117229],
       [0.78145   , 0.35673073, 0.4724919 ],
       [0.35913307, 0.82487671, 0.9308465 ],
       [0.55573379, 0.39736186, 0.91822155],
       [0.89280326, 0.99244444, 0.93928608],
       [0.17169872, 0.39982916, 0.36104625],
       [0.62088311, 0.50933936, 0.14757552],
       [0.46270758, 0.927096  , 0.47591423]])

In [123]:
a.reshape(3, 8)

array([[0.66139009, 0.55109088, 0.44117229, 0.78145   , 0.35673073,
        0.4724919 , 0.35913307, 0.82487671],
       [0.9308465 , 0.55573379, 0.39736186, 0.91822155, 0.89280326,
        0.99244444, 0.93928608, 0.17169872],
       [0.39982916, 0.36104625, 0.62088311, 0.50933936, 0.14757552,
        0.46270758, 0.927096  , 0.47591423]])

In [125]:
a.reshape(1, 24)

array([[0.66139009, 0.55109088, 0.44117229, 0.78145   , 0.35673073,
        0.4724919 , 0.35913307, 0.82487671, 0.9308465 , 0.55573379,
        0.39736186, 0.91822155, 0.89280326, 0.99244444, 0.93928608,
        0.17169872, 0.39982916, 0.36104625, 0.62088311, 0.50933936,
        0.14757552, 0.46270758, 0.927096  , 0.47591423]])

In [126]:
a.reshape(2, 12)

array([[0.66139009, 0.55109088, 0.44117229, 0.78145   , 0.35673073,
        0.4724919 , 0.35913307, 0.82487671, 0.9308465 , 0.55573379,
        0.39736186, 0.91822155],
       [0.89280326, 0.99244444, 0.93928608, 0.17169872, 0.39982916,
        0.36104625, 0.62088311, 0.50933936, 0.14757552, 0.46270758,
        0.927096  , 0.47591423]])

In [128]:
a.reshape(3, -1).shape

(3, 8)

In [129]:
a.reshape(8, -1)

array([[0.66139009, 0.55109088, 0.44117229],
       [0.78145   , 0.35673073, 0.4724919 ],
       [0.35913307, 0.82487671, 0.9308465 ],
       [0.55573379, 0.39736186, 0.91822155],
       [0.89280326, 0.99244444, 0.93928608],
       [0.17169872, 0.39982916, 0.36104625],
       [0.62088311, 0.50933936, 0.14757552],
       [0.46270758, 0.927096  , 0.47591423]])

In [131]:
a.reshape(-1, 1)

array([[0.66139009],
       [0.55109088],
       [0.44117229],
       [0.78145   ],
       [0.35673073],
       [0.4724919 ],
       [0.35913307],
       [0.82487671],
       [0.9308465 ],
       [0.55573379],
       [0.39736186],
       [0.91822155],
       [0.89280326],
       [0.99244444],
       [0.93928608],
       [0.17169872],
       [0.39982916],
       [0.36104625],
       [0.62088311],
       [0.50933936],
       [0.14757552],
       [0.46270758],
       [0.927096  ],
       [0.47591423]])

In [132]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

In [133]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [134]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
np.hstack((a1, a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.hstack((a1, a1))


array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [138]:
np.vstack((a1, a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [140]:
np.stack((a1, a2), axis = 1)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [143]:
np.hsplit?

Signature:       np.hsplit(ary, indices_or_sections)
Call signature:  np.hsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function hsplit at 0x00000285335014E0>
File:            c:\users\admin\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.],
       [  6.,   7.],
       [10.,

In [148]:
np.hsplit(a1, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [145]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
np.vsplit?

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x0000028533501580>
File:            c:\users\admin\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
>>> np.vsplit(x, np.array([3, 6]))
[array

In [151]:
x = np.arange(16.0).reshape(4, 4)

In [152]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [154]:
np.vsplit(x, 4)

[array([[0., 1., 2., 3.]]),
 array([[4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]])]

In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(6, 4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a[1 : 3, 1 : 3]

array([[ 5,  6],
       [ 9, 10]])

In [6]:
a[:, [1, 3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
# data filter
len(a[a > 10])

13

In [12]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [15]:
a[(a > 15) & (a % 2 == 0)]

array([16, 18, 20, 22])

In [18]:
a[(a % 2!= 0)]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [19]:
a[~(a % 5 == 0)]

array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 13, 14, 16, 17, 18, 19, 21,
       22, 23])

In [20]:
# working with mathematical formula

In [21]:
a = np.array([[1, 2], 
              [3, 4]])

In [22]:
np.mean(a)

2.5

In [23]:
np.median(a)

2.5

In [24]:
np.std(a)

1.118033988749895

In [25]:
np.var(a)

1.25

In [26]:
(np.std(a))**2

1.2500000000000002

In [ ]:
# var = std**2

In [28]:
np.sin(45)

0.8509035245341184

In [ ]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [31]:
sigmoid(a) # [0 - 1]

array([[0.73105858, 0.88079708],
       [0.95257413, 0.98201379]])

In [32]:
np.sum(a)

10

In [34]:
a

array([[1, 2],
       [3, 4]])

In [33]:
np.sum(a, axis = 0)

array([4, 6])

In [35]:
np.sum(a, axis = 1)

array([3, 7])

In [36]:
# random initialization of matrix

In [53]:
np.random.random((3, 4))

array([[0.2212652 , 0.2236259 , 0.0852407 , 0.3944998 ],
       [0.20368884, 0.68194059, 0.23910102, 0.32753338],
       [0.43846146, 0.53536388, 0.35148016, 0.00512023]])

In [38]:
np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method

In [54]:
# P(getting zero) = 1/infinity

In [56]:
np.random.rand(3, 4)

array([[0.39227621, 0.15862613, 0.24951972, 0.12026302],
       [0.17908095, 0.29929573, 0.33447694, 0.51818662],
       [0.3151499 , 0.58384218, 0.73516007, 0.24228839]])

In [57]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method

In [58]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [59]:
np.random.randn(3, 4)

array([[-1.44730584,  0.56806552,  0.38982469, -1.0225211 ],
       [ 0.04563839,  0.90235524, -0.70686921,  0.65460694],
       [ 0.57619128,  1.14101028,  1.94322268, -0.04097543]])

In [66]:
np.random.randint(0, 100, 10)

array([68, 19,  8, 91, 15, 31, 56, 21, 86, 66])

In [68]:
np.random.randint(0, 100, (3, 4))

array([[27, 59, 87, 47],
       [ 0, 50, 23, 40],
       [39, 39, 78, 13]])

In [69]:
a

array([[1, 2],
       [3, 4]])

In [70]:
np.linalg.det(a)

-2.0000000000000004

In [71]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [75]:
a = np.array([[0, 0],
              [1, 0]])

In [81]:
np.ndim(a)

2

In [76]:
np.linalg.det(a)

0.0

In [83]:
# np.linalg.inv(a)

In [84]:
a

array([[0, 0],
       [1, 0]])

In [90]:
a = np.array([1, 2])
b = np.array([4, 5])

In [ ]:
np.linalg.norm(a)  # distance of a from origin point(0, 0)

2.23606797749979

In [88]:
np.linalg.norm(b)

6.4031242374328485

In [89]:
np.linalg.norm(a-b)

4.242640687119285

In [91]:
a-b

array([-3, -3])

In [93]:
((-3 - 0) ** 2 + (-3 - 0)**2)**0.5

4.242640687119285